run-day3-part1:
	cargo run --bin day3_part1

run-day-3-part2:
	cargo run --bin day3_part2

run-day-4-part1:
	cargo run --bin day4_part1

run-day-4-part2:
	cargo run --bin day4_part2

run-day-5-part1:
	cargo run --bin day5_part1

run-day-6-part1:
	cargo run --bin day6_part1

run-day-6-part1-py:
	python3 src/day6/part1/main.py

run-day-7:
	cargo run --bin day7